
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Rokers
subtitle: "La prima community italiana per promuovere la robotica in tutte le sue forme e declinazioni"
url: "https://rokers.io"

baseurl: "https://rokers.io"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
plugins_dir: [jekyll-admin, jekyll-seo-tag]
 # This will require each of these plugins automatically.
group: jekyll_plugins do
   gem "jekyll-admin"
   gem "jekyll-seo-tag"
 end
gems:
  - jekyll-seo-tag
  - jekyll-feed
